-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2025-12-01 15:57:03 SEÈ
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE adresy (
    idadresy               INTEGER NOT NULL,
    postovnismerovacicislo CHAR(5) NOT NULL,
    ulice                  VARCHAR2(30) NOT NULL,
    cislopopisne           INTEGER NOT NULL,
    obec                   VARCHAR2(30) NOT NULL,
    zeme                   VARCHAR2(30) NOT NULL
);

ALTER TABLE adresy ADD CONSTRAINT adresa_pk PRIMARY KEY ( idadresy );

CREATE TABLE automobily (
    idprostredku    INTEGER NOT NULL,
    poznavaciznacka VARCHAR2(8) NOT NULL
);

ALTER TABLE automobily ADD CONSTRAINT automobil_pk PRIMARY KEY ( idprostredku );

ALTER TABLE automobily ADD CONSTRAINT automobily__un UNIQUE ( poznavaciznacka );

CREATE TABLE barvy (
    idbarvy INTEGER NOT NULL,
    nazev   VARCHAR2(20) NOT NULL
);

ALTER TABLE barvy ADD CONSTRAINT barva_pk PRIMARY KEY ( idbarvy );

CREATE TABLE dopravni_prostredky (
    idprostredku  INTEGER NOT NULL,
    idbarvy       INTEGER NOT NULL,
    idpolicisty   INTEGER NOT NULL,
    discriminator CHAR(1) NOT NULL,
    poznamka      VARCHAR2(30)
);

ALTER TABLE dopravni_prostredky
    ADD CONSTRAINT fkarc_1_lov CHECK ( discriminator IN ( '1', '0', '2' ) );

ALTER TABLE dopravni_prostredky ADD CONSTRAINT dopravni_prostredek_pk PRIMARY KEY ( idprostredku );

CREATE TABLE evidence_hlidek (
    idhlidky    INTEGER NOT NULL,
    idpolicisty INTEGER NOT NULL,
    datum       DATE NOT NULL,
    casod       DATE NOT NULL,
    casdo       DATE NOT NULL
);

ALTER TABLE evidence_hlidek ADD CONSTRAINT evidence_hlidky_pk PRIMARY KEY ( idpolicisty,
                                                                            idhlidky );

CREATE TABLE evidence_r_prukazu (
    idtypu  INTEGER NOT NULL,
    cislorp INTEGER NOT NULL
);

ALTER TABLE evidence_r_prukazu ADD CONSTRAINT evidence_r_prukazu PRIMARY KEY ( idtypu,
                                                                               cislorp );

CREATE TABLE evidence_zasahu (
    idzasahu INTEGER NOT NULL,
    idhlidky INTEGER NOT NULL
);

ALTER TABLE evidence_zasahu ADD CONSTRAINT evidence_zasahu PRIMARY KEY ( idzasahu,
                                                                         idhlidky );

CREATE TABLE hlidky (
    idhlidky    INTEGER NOT NULL,
    nazevhlidky VARCHAR2(30) NOT NULL,
    idtypu      INTEGER NOT NULL
);

ALTER TABLE hlidky ADD CONSTRAINT hlidka_pk PRIMARY KEY ( idhlidky );

CREATE TABLE hodnosti (
    idhodnosti INTEGER NOT NULL,
    nazev      VARCHAR2(30) NOT NULL
);

ALTER TABLE hodnosti ADD CONSTRAINT hodnost_pk PRIMARY KEY ( idhodnosti );

CREATE TABLE komunikace (
    idkomunikace INTEGER NOT NULL,
    zprava       VARCHAR2(30) NOT NULL,
    datum        DATE NOT NULL,
    poznamka     VARCHAR2(30),
    idobcana     INTEGER NOT NULL,
    idprestupku  INTEGER NOT NULL
);

ALTER TABLE komunikace ADD CONSTRAINT komunikace_pk PRIMARY KEY ( idkomunikace );

CREATE TABLE kone (
    idprostredku  INTEGER NOT NULL,
    jmeno         VARCHAR2(30) NOT NULL,
    datumnarozeni DATE NOT NULL
);

ALTER TABLE kone ADD CONSTRAINT kun_pk PRIMARY KEY ( idprostredku );

CREATE TABLE logovaci_tabulka (
    id           INTEGER NOT NULL,
    nazevtabulky VARCHAR2(100) NOT NULL,
    akce         VARCHAR2(20) NOT NULL,
    old          VARCHAR2(4000) NOT NULL,
    new          VARCHAR2(4000) NOT NULL,
    datum        DATE NOT NULL
);

ALTER TABLE logovaci_tabulka ADD CONSTRAINT logovaci_tabulka_pk PRIMARY KEY ( id );

CREATE TABLE motocykly (
    idprostredku    INTEGER NOT NULL,
    poznavaciznacka VARCHAR2(7) NOT NULL
);

COMMENT ON COLUMN motocykly.poznavaciznacka IS
    'podle internetu mají 7 znakù';

ALTER TABLE motocykly ADD CONSTRAINT motocykl_pk PRIMARY KEY ( idprostredku );

ALTER TABLE motocykly ADD CONSTRAINT motocykly__un UNIQUE ( poznavaciznacka );

CREATE TABLE obcane (
    idobcana    INTEGER NOT NULL,
    jmeno       VARCHAR2(30) NOT NULL,
    prijmeni    VARCHAR2(30) NOT NULL,
    cisloop     INTEGER NOT NULL,
    poznamka    VARCHAR2(30),
    idadresy    INTEGER NOT NULL,
    iduzivatele INTEGER NOT NULL
);

CREATE UNIQUE INDEX obcan__idxv1 ON
    obcane (
        iduzivatele
    ASC );

ALTER TABLE obcane ADD CONSTRAINT obcan_pk PRIMARY KEY ( idobcana );

CREATE TABLE okrsky (
    idokrsku INTEGER NOT NULL,
    nazev    VARCHAR2(30) NOT NULL
);

ALTER TABLE okrsky ADD CONSTRAINT okrsek_pk PRIMARY KEY ( idokrsku );

CREATE TABLE okrsky_hlidky (
    idhlidky INTEGER NOT NULL,
    idokrsku INTEGER NOT NULL
);

ALTER TABLE okrsky_hlidky ADD CONSTRAINT relation_22_pk PRIMARY KEY ( idhlidky,
                                                                      idokrsku );

CREATE TABLE opravneni (
    idopravneni    INTEGER NOT NULL,
    nazevopravneni VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN opravneni.nazevopravneni IS
    'administrator/policista/obcan (administrator musí být policista)';

ALTER TABLE opravneni ADD CONSTRAINT opravneni_pk PRIMARY KEY ( idopravneni );

ALTER TABLE opravneni ADD CONSTRAINT opravneni__un UNIQUE ( nazevopravneni );

CREATE TABLE policejni_stanice (
    idstanice INTEGER NOT NULL,
    nazev     VARCHAR2(30) NOT NULL,
    poznamka  VARCHAR2(30)
);

ALTER TABLE policejni_stanice ADD CONSTRAINT policejni_stanice_pk PRIMARY KEY ( idstanice );

CREATE TABLE policiste (
    idpolicisty   INTEGER NOT NULL,
    jmeno         VARCHAR2(30) NOT NULL,
    prijmeni      VARCHAR2(30) NOT NULL,
    datumnarozeni DATE NOT NULL,
    plat          INTEGER NOT NULL,
    idstanice     INTEGER NOT NULL,
    idhodnosti    INTEGER NOT NULL,
    poznamka      VARCHAR2(30),
    iduzivatele   INTEGER NOT NULL,
    idnadrizeneho INTEGER
);

CREATE UNIQUE INDEX policista__idxv1 ON
    policiste (
        iduzivatele
    ASC );

ALTER TABLE policiste ADD CONSTRAINT policista_pk PRIMARY KEY ( idpolicisty );

ALTER TABLE policiste ADD CONSTRAINT fk_policiste_nadrizeny FOREIGN KEY (idnadrizeneho) REFERENCES policiste (idpolicisty)
ON DELETE SET NULL;

CREATE TABLE prestupky (
    idprestupku     INTEGER NOT NULL,
    idzasahu        INTEGER NOT NULL,
    idtypuprestupku INTEGER NOT NULL,
    poznamka        VARCHAR2(30)
);

ALTER TABLE prestupky ADD CONSTRAINT prestupek_pk PRIMARY KEY ( idprestupku );

CREATE TABLE prestupky_obcanu (
    idobcana    INTEGER NOT NULL,
    idprestupku INTEGER NOT NULL,
    datum       DATE NOT NULL
);

ALTER TABLE prestupky_obcanu ADD CONSTRAINT prestupky_obcana_pk PRIMARY KEY ( idobcana,
                                                                              idprestupku );

CREATE TABLE ridicske_prukazy (
    cislorp     INTEGER NOT NULL,
    platnostdo  DATE NOT NULL,
    idpolicisty INTEGER
);

CREATE UNIQUE INDEX ridicsky_prukaz__idx ON
    ridicske_prukazy (
        idpolicisty
    ASC );

ALTER TABLE ridicske_prukazy ADD CONSTRAINT ridicsky_prukaz_pk PRIMARY KEY ( cislorp );

ALTER TABLE ridicske_prukazy ADD CONSTRAINT ridicske_prukazy__un UNIQUE ( idpolicisty );

CREATE TABLE typy_hlidky (
    idtypu INTEGER NOT NULL,
    nazev  VARCHAR2(30) NOT NULL
);

ALTER TABLE typy_hlidky ADD CONSTRAINT typ_hlidky_pk PRIMARY KEY ( idtypu );

CREATE TABLE typy_prestupku (
    idtypuprestupku INTEGER NOT NULL,
    prestupek       VARCHAR2(20) NOT NULL
);

ALTER TABLE typy_prestupku ADD CONSTRAINT typ_prestupku_pk PRIMARY KEY ( idtypuprestupku );

CREATE TABLE typy_ridicskeho_prukazu (
    idtypu INTEGER NOT NULL,
    typ    VARCHAR2(1) NOT NULL
);

ALTER TABLE typy_ridicskeho_prukazu ADD CONSTRAINT typ_ridicskeho_prukazu_pk PRIMARY KEY ( idtypu );

CREATE TABLE uzivatele (
    iduzivatele       INTEGER NOT NULL,
    prihlasovacijmeno VARCHAR2(50 CHAR) NOT NULL,
    heslo             VARCHAR2(50 CHAR) NOT NULL,
    idpolicisty       INTEGER,
    idobcana          INTEGER,
    idopravneni       INTEGER NOT NULL
);

alter table uzivatele add obrazek blob;

COMMENT ON COLUMN uzivatele.heslo IS
    'hash hesla';

CREATE UNIQUE INDEX uzivatel__idx ON
    uzivatele (
        idpolicisty
    ASC );

CREATE UNIQUE INDEX uzivatel__idxv1 ON
    uzivatele (
        idobcana
    ASC );

ALTER TABLE uzivatele ADD CONSTRAINT uzivatel_pk PRIMARY KEY ( iduzivatele );

ALTER TABLE uzivatele ADD CONSTRAINT uzivatele__un UNIQUE ( PRIHLASOVACIJMENO );

CREATE TABLE zasahy (
    idzasahu INTEGER NOT NULL,
    datum    DATE NOT NULL,
    cas      DATE NOT NULL,
    popis    VARCHAR2(50) NOT NULL,
    idadresy INTEGER NOT NULL
);

ALTER TABLE zasahy ADD CONSTRAINT zasah_pk PRIMARY KEY ( idzasahu );

ALTER TABLE automobily
    ADD CONSTRAINT auto_dopravni_prostredek_fk FOREIGN KEY ( idprostredku )
        REFERENCES dopravni_prostredky ( idprostredku )
		on delete cascade;

ALTER TABLE dopravni_prostredky
    ADD CONSTRAINT barva_fk FOREIGN KEY ( idbarvy )
        REFERENCES barvy ( idbarvy )
		on delete cascade;

ALTER TABLE evidence_hlidek
    ADD CONSTRAINT evidence_hlidky_hlidka_fk FOREIGN KEY ( idhlidky )
        REFERENCES hlidky ( idhlidky );

ALTER TABLE evidence_hlidek
    ADD CONSTRAINT evidence_hlidky_policista_fk FOREIGN KEY ( idpolicisty )
        REFERENCES policiste ( idpolicisty )
		on delete cascade;

ALTER TABLE evidence_zasahu
    ADD CONSTRAINT evidence_zasahu_hlidka_fk FOREIGN KEY ( idhlidky )
        REFERENCES hlidky ( idhlidky );

ALTER TABLE evidence_zasahu
    ADD CONSTRAINT evidence_zasahu_zasah_fk FOREIGN KEY ( idzasahu )
        REFERENCES zasahy ( idzasahu );

ALTER TABLE hlidky
    ADD CONSTRAINT hlidka_typ_hlidky_fk FOREIGN KEY ( idtypu )
        REFERENCES typy_hlidky ( idtypu );

ALTER TABLE komunikace
    ADD CONSTRAINT komunikace_prestupky_obcana_fk FOREIGN KEY ( idobcana,
                                                                idprestupku )
        REFERENCES prestupky_obcanu ( idobcana,
                                      idprestupku )
	on delete cascade;

ALTER TABLE kone
    ADD CONSTRAINT kun_dopravni_prostredek_fk FOREIGN KEY ( idprostredku )
        REFERENCES dopravni_prostredky ( idprostredku )
		on delete cascade;

ALTER TABLE motocykly
    ADD CONSTRAINT moto_dopravni_prostredek_fk FOREIGN KEY ( idprostredku )
        REFERENCES dopravni_prostredky ( idprostredku )
		on delete cascade;

ALTER TABLE obcane
    ADD CONSTRAINT obcan_adresa_fk FOREIGN KEY ( idadresy )
        REFERENCES adresy ( idadresy );

ALTER TABLE obcane
    ADD CONSTRAINT obcan_uzivatel_fk FOREIGN KEY ( iduzivatele )
        REFERENCES uzivatele ( iduzivatele )
	on delete cascade;

ALTER TABLE dopravni_prostredky
    ADD CONSTRAINT policista_fk FOREIGN KEY ( idpolicisty )
        REFERENCES policiste ( idpolicisty )
	on delete cascade;

ALTER TABLE policiste
    ADD CONSTRAINT policista_hodnost_fk FOREIGN KEY ( idhodnosti )
        REFERENCES hodnosti ( idhodnosti );

ALTER TABLE policiste
    ADD CONSTRAINT policista_policejni_stanice_fk FOREIGN KEY ( idstanice )
        REFERENCES policejni_stanice ( idstanice );

ALTER TABLE policiste
    ADD CONSTRAINT policista_uzivatel_fk FOREIGN KEY ( iduzivatele )
        REFERENCES uzivatele ( iduzivatele )
		on delete cascade;

ALTER TABLE prestupky
    ADD CONSTRAINT prestupek_typ_prestupku_fk FOREIGN KEY ( idtypuprestupku )
        REFERENCES typy_prestupku ( idtypuprestupku );

ALTER TABLE prestupky
    ADD CONSTRAINT prestupek_zasah_fk FOREIGN KEY ( idzasahu )
        REFERENCES zasahy ( idzasahu );

ALTER TABLE prestupky_obcanu
    ADD CONSTRAINT prestupky_obcana_obcan_fk FOREIGN KEY ( idobcana )
        REFERENCES obcane ( idobcana )
	on delete cascade;

ALTER TABLE prestupky_obcanu
    ADD CONSTRAINT prestupky_obcana_prestupek_fk FOREIGN KEY ( idprestupku )
        REFERENCES prestupky ( idprestupku );

ALTER TABLE okrsky_hlidky
    ADD CONSTRAINT relation_22_hlidka_fk FOREIGN KEY ( idhlidky )
        REFERENCES hlidky ( idhlidky );

ALTER TABLE okrsky_hlidky
    ADD CONSTRAINT relation_22_okrsek_fk FOREIGN KEY ( idokrsku )
        REFERENCES okrsky ( idokrsku );

ALTER TABLE ridicske_prukazy
    ADD CONSTRAINT ridicsky_prukaz_policista_fk FOREIGN KEY ( idpolicisty )
        REFERENCES policiste ( idpolicisty )
		on delete cascade;

ALTER TABLE evidence_r_prukazu
    ADD CONSTRAINT typy_ridicske_prukazy_fk FOREIGN KEY ( cislorp )
        REFERENCES ridicske_prukazy ( cislorp )
		on delete cascade;

ALTER TABLE evidence_r_prukazu
    ADD CONSTRAINT typy_ridicskeho_prukazu_fk FOREIGN KEY ( idtypu )
        REFERENCES typy_ridicskeho_prukazu ( idtypu );

ALTER TABLE uzivatele
    ADD CONSTRAINT uzivatel_opravneni_fk FOREIGN KEY ( idopravneni )
        REFERENCES opravneni ( idopravneni );

ALTER TABLE zasahy
    ADD CONSTRAINT zasah_adresa_fk FOREIGN KEY ( idadresy )
        REFERENCES adresy ( idadresy );

CREATE OR REPLACE TRIGGER fknto_ridicske_prukazy BEFORE
    UPDATE OF idpolicisty ON ridicske_prukazy
    FOR EACH ROW
BEGIN
    IF :old.idpolicisty IS NOT NULL THEN
        raise_application_error(-20225, 'Non Transferable FK constraint RIDICSKY_PRUKAZ_POLICISTA_FK on table RIDICSKE_PRUKAZY is violated'
        );
    END IF;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_kone BEFORE
    INSERT OR UPDATE OF idprostredku ON kone
    FOR EACH ROW
DECLARE
    d CHAR(1);
BEGIN
    SELECT
        a.discriminator
    INTO d
    FROM
        dopravni_prostredky a
    WHERE
        a.idprostredku = :new.idprostredku;

    IF ( d IS NULL OR d <> '1' ) THEN
        raise_application_error(-20223, 'FK KUN_DOPRAVNI_PROSTREDEK_FK in Table KONE violates Arc constraint on Table DOPRAVNI_PROSTREDKY - discriminator column discriminator doesn''t have value ''1'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_automobily BEFORE
    INSERT OR UPDATE OF idprostredku ON automobily
    FOR EACH ROW
DECLARE
    d CHAR(1);
BEGIN
    SELECT
        a.discriminator
    INTO d
    FROM
        dopravni_prostredky a
    WHERE
        a.idprostredku = :new.idprostredku;

    IF ( d IS NULL OR d <> '0' ) THEN
        raise_application_error(-20223, 'FK AUTO_DOPRAVNI_PROSTREDEK_FK in Table AUTOMOBILY violates Arc constraint on Table DOPRAVNI_PROSTREDKY - discriminator column discriminator doesn''t have value ''0'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_motocykly BEFORE
    INSERT OR UPDATE OF idprostredku ON motocykly
    FOR EACH ROW
DECLARE
    d CHAR(1);
BEGIN
    SELECT
        a.discriminator
    INTO d
    FROM
        dopravni_prostredky a
    WHERE
        a.idprostredku = :new.idprostredku;

    IF ( d IS NULL OR d <> '2' ) THEN
        raise_application_error(-20223, 'FK MOTO_DOPRAVNI_PROSTREDEK_FK in Table MOTOCYKLY violates Arc constraint on Table DOPRAVNI_PROSTREDKY - discriminator column discriminator doesn''t have value ''2'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE SEQUENCE adresy_idadresy_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER adresy_idadresy_trg BEFORE
    INSERT ON adresy
    FOR EACH ROW
    WHEN ( new.idadresy IS NULL )
BEGIN
    :new.idadresy := adresy_idadresy_seq.nextval;
END;
/

CREATE SEQUENCE barvy_idbarvy_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER barvy_idbarvy_trg BEFORE
    INSERT ON barvy
    FOR EACH ROW
    WHEN ( new.idbarvy IS NULL )
BEGIN
    :new.idbarvy := barvy_idbarvy_seq.nextval;
END;
/

CREATE SEQUENCE dopravni_prostredky_idprostred START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER dopravni_prostredky_idprostred BEFORE
    INSERT ON dopravni_prostredky
    FOR EACH ROW
    WHEN ( new.idprostredku IS NULL )
BEGIN
    :new.idprostredku := dopravni_prostredky_idprostred.nextval;
END;
/

CREATE SEQUENCE hlidky_idhlidky_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER hlidky_idhlidky_trg BEFORE
    INSERT ON hlidky
    FOR EACH ROW
    WHEN ( new.idhlidky IS NULL )
BEGIN
    :new.idhlidky := hlidky_idhlidky_seq.nextval;
END;
/

CREATE SEQUENCE hodnosti_idhodnosti_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER hodnosti_idhodnosti_trg BEFORE
    INSERT ON hodnosti
    FOR EACH ROW
    WHEN ( new.idhodnosti IS NULL )
BEGIN
    :new.idhodnosti := hodnosti_idhodnosti_seq.nextval;
END;
/

CREATE SEQUENCE komunikace_idkomunikace_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER komunikace_idkomunikace_trg BEFORE
    INSERT ON komunikace
    FOR EACH ROW
    WHEN ( new.idkomunikace IS NULL )
BEGIN
    :new.idkomunikace := komunikace_idkomunikace_seq.nextval;
END;
/

CREATE SEQUENCE logovaci_tabulka_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER logovaci_tabulka_id_trg BEFORE
    INSERT ON logovaci_tabulka
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := logovaci_tabulka_id_seq.nextval;
END;
/

CREATE SEQUENCE obcane_idobcana_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER obcane_idobcana_trg BEFORE
    INSERT ON obcane
    FOR EACH ROW
    WHEN ( new.idobcana IS NULL )
BEGIN
    :new.idobcana := obcane_idobcana_seq.nextval;
END;
/

CREATE SEQUENCE okrsky_idokrsku_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER okrsky_idokrsku_trg BEFORE
    INSERT ON okrsky
    FOR EACH ROW
    WHEN ( new.idokrsku IS NULL )
BEGIN
    :new.idokrsku := okrsky_idokrsku_seq.nextval;
END;
/

CREATE SEQUENCE opravneni_idopravneni_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER opravneni_idopravneni_trg BEFORE
    INSERT ON opravneni
    FOR EACH ROW
    WHEN ( new.idopravneni IS NULL )
BEGIN
    :new.idopravneni := opravneni_idopravneni_seq.nextval;
END;
/

CREATE SEQUENCE policejni_stanice_idstanice START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER policejni_stanice_idstanice BEFORE
    INSERT ON policejni_stanice
    FOR EACH ROW
    WHEN ( new.idstanice IS NULL )
BEGIN
    :new.idstanice := policejni_stanice_idstanice.nextval;
END;
/

CREATE SEQUENCE policiste_idpolicisty_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER policiste_idpolicisty_trg BEFORE
    INSERT ON policiste
    FOR EACH ROW
    WHEN ( new.idpolicisty IS NULL )
BEGIN
    :new.idpolicisty := policiste_idpolicisty_seq.nextval;
END;
/

CREATE SEQUENCE prestupky_idprestupku_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER prestupky_idprestupku_trg BEFORE
    INSERT ON prestupky
    FOR EACH ROW
    WHEN ( new.idprestupku IS NULL )
BEGIN
    :new.idprestupku := prestupky_idprestupku_seq.nextval;
END;
/

CREATE SEQUENCE typy_hlidky_idtypu_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER typy_hlidky_idtypu_trg BEFORE
    INSERT ON typy_hlidky
    FOR EACH ROW
    WHEN ( new.idtypu IS NULL )
BEGIN
    :new.idtypu := typy_hlidky_idtypu_seq.nextval;
END;
/

CREATE SEQUENCE typy_prestupku_idtypuprestupku START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER typy_prestupku_idtypuprestupku BEFORE
    INSERT ON typy_prestupku
    FOR EACH ROW
    WHEN ( new.idtypuprestupku IS NULL )
BEGIN
    :new.idtypuprestupku := typy_prestupku_idtypuprestupku.nextval;
END;
/

CREATE SEQUENCE typy_ridicskeho_prukazu_idtypu START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER typy_ridicskeho_prukazu_idtypu BEFORE
    INSERT ON typy_ridicskeho_prukazu
    FOR EACH ROW
    WHEN ( new.idtypu IS NULL )
BEGIN
    :new.idtypu := typy_ridicskeho_prukazu_idtypu.nextval;
END;
/

CREATE SEQUENCE uzivatele_iduzivatele_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER uzivatele_iduzivatele_trg BEFORE
    INSERT ON uzivatele
    FOR EACH ROW
    WHEN ( new.iduzivatele IS NULL )
BEGIN
    :new.iduzivatele := uzivatele_iduzivatele_seq.nextval;
END;
/

CREATE SEQUENCE zasahy_idzasahu_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER zasahy_idzasahu_trg BEFORE
    INSERT ON zasahy
    FOR EACH ROW
    WHEN ( new.idzasahu IS NULL )
BEGIN
    :new.idzasahu := zasahy_idzasahu_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            27
-- CREATE INDEX                             5
-- ALTER TABLE                             60
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          22
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         18
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
