insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('78832', 'Waywood', 482, 'Staré Mìsto', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('51301', 'Manitowish', 228, 'Rokytnice nad Jizerou', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('38486', 'Bluejay', 237, 'Vacov', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('51211', 'Cascade', 91, 'Vysoké nad Jizerou', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('19800', 'Nobel', 463, 'Èerný Most', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('56992', 'Jenifer', 65, 'Bystré', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('28907', 'Forest Run', 273, 'Libice nad Cidlinou', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('46331', 'Lawn', 38, 'Chrastava', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('73953', 'Russell', 115, 'Komorní Lhotka', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('33023', 'Lindbergh', 486, 'Nýøany', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('59213', 'Thackeray', 477, 'Bohdalov', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('69145', 'Daystar', 138, 'Podivín', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('67921', 'Northview', 460, 'Èerná Hora', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('41147', 'Kings', 78, 'Polepy', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('54981', 'Helena', 124, 'Mezimìstí', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('74265', 'Duke', 413, 'Rybí', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('26223', 'Declaration', 110, 'Jince', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('38282', 'Armistice', 381, 'Benešov nad Èernou', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('53803', 'Service', 108, 'Heømanùv Mìstec', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('36225', 'Vidon', 208, 'Nová Role', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('54931', 'Fuller', 52, 'Hronov', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('25167', 'Blackbird', 59, 'Pyšely', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('34535', 'Del Mar', 22, 'Postøekov', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('53304', 'Loftsgordon', 493, 'Sezemice', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('73995', 'Veith', 443, 'Nýdek', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('25065', 'Bluejay', 165, 'Líbeznice', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('69666', 'Ryan', 217, 'Sudomìøice', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('37372', 'Buell', 394, 'Lišov', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('73914', 'Cordelia', 216, 'Ostravice', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('67961', 'Everett', 320, 'Letovice', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('33301', 'Clemons', 406, 'Stod', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('66443', 'Westend', 348, 'Želešice', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('67501', 'Moulton', 130, 'Vladislav', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('69163', 'Huxley', 442, 'Velké Nìmèice', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('75657', 'Roth', 228, 'Horní Beèva', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('78962', 'Nobel', 393, 'Bohutín', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('75501', 'North', 420, 'Rokytnice', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('67169', 'Acker', 366, 'Hevlín', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('38901', 'Memorial', 2, 'Vod ?any', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('78832', 'Northview', 331, 'Staré Mìsto', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('46401', 'Dwight', 184, 'Viš ?ova', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('56161', 'Spohn', 151, 'Èervená Voda', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('78901', 'Hauk', 113, 'Zvole', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('34802', 'Prentice', 62, 'Borovany', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('14700', 'Miller', 35, 'Hodkovièky', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('69605', 'Basil', 403, 'Milotice', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('50351', 'Stuart', 317, 'Chlumec nad Cidlinou', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('68765', 'Anderson', 33, 'Strání', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('54234', 'Kropf', 435, 'Malé Svato ?ovice', 'Czech Republic');
insert into adresy (postovnismerovacicislo, ulice, cislopopisne, obec, zeme) values ('29501', 'Helena', 24, 'Mnichovo Hradištì', 'Czech Republic');

insert into typy_hlidky(nazev) values ('pesi');
insert into typy_hlidky(nazev) values ('motocykl');
insert into typy_hlidky(nazev) values ('automobil');
insert into typy_hlidky(nazev) values ('kun');

insert into barvy (nazev) values ('bila');
insert into barvy (nazev) values ('modra');
insert into barvy (nazev) values ('cerna');
insert into barvy (nazev) values ('cervena');
insert into barvy (nazev) values ('zluta');
insert into barvy (nazev) values ('zelena');

insert into hodnosti(nazev) VALUES('brigadni general');
insert into hodnosti(nazev) VALUES('generalmajor');
insert into hodnosti(nazev) VALUES('generalporucik');
insert into hodnosti(nazev) VALUES('kapitan');
insert into hodnosti(nazev) VALUES('major');
insert into hodnosti(nazev) VALUES('nadpraporcik');
insert into hodnosti(nazev) VALUES('nadstrazmistr');
insert into hodnosti(nazev) VALUES('plukovnik');
insert into hodnosti(nazev) VALUES('podplukovnik');
insert into hodnosti(nazev) VALUES('podpraporcik');
insert into hodnosti(nazev) VALUES('praporcik');
insert into hodnosti(nazev) VALUES('rotny');
insert into hodnosti(nazev) VALUES('strazmistr');

insert into typy_ridicskeho_prukazu(typ) values('A');
insert into typy_ridicskeho_prukazu(typ) values('B');
insert into typy_ridicskeho_prukazu(typ) values('C');
insert into typy_ridicskeho_prukazu(typ) values('D');
insert into typy_ridicskeho_prukazu(typ) values('T');

insert into okrsky(nazev) values('Dubina');
insert into okrsky(nazev) values('Dukla');
insert into okrsky(nazev) values('Hostovice');
insert into okrsky(nazev) values('Pardubicky');
insert into okrsky(nazev) values('Polabiny');
insert into okrsky(nazev) values('Rosice');
insert into okrsky(nazev) values('Stred');
insert into okrsky(nazev) values('Svitkov');

insert into typy_prestupku(prestupek) values('domaci nasili');
insert into typy_prestupku(prestupek) values('jizda pod vlivem');
insert into typy_prestupku(prestupek) values('moceni na verejnosti');
insert into typy_prestupku(prestupek) values('napadeni');
insert into typy_prestupku(prestupek) values('rychla jizda');

insert into policejni_stanice(nazev) values('Pardubice 1');
insert into policejni_stanice(nazev) values('Pardubice 2');
insert into policejni_stanice(nazev) values('Pardubice 3');
insert into policejni_stanice(nazev) values('Pardubice 4');
insert into policejni_stanice(nazev) values('Pardubice 5');

insert into opravneni(nazevopravneni) values('policista');
insert into opravneni(nazevopravneni) values('obcan');
insert into opravneni(nazevopravneni) values('administrator');

insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Evangelina', 'Eagleston', '05/05/1999', 47662, 1, 2, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Roman', 'Royden', '19/07/1993', 91384, 4, 11, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Wallis', 'Date', '17/12/1974', 51820, 2, 3, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Chucho', 'Pogosian', '03/10/2000', 44955, 5, 2, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Edita', 'Reglar', '26/11/1970', 71092, 2, 4, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Marga', 'Francombe', '04/09/1982', 98526, 1, 5, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Charley', 'Bouts', '14/02/1981', 71046, 2, 3, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Jayne', 'Robjohns', '23/05/1998', 39997, 1, 3, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Alina', 'Marland', '16/07/1997', 53897, 3, 6, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Daniela', 'Whitchurch', '18/11/1971', 57545, 1, 8, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Lucine', 'Peltz', '08/07/1989', 89451, 1, 4, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Alvira', 'Zohrer', '02/12/1983', 50943, 5, 5, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Eugenie', 'Rioch', '17/04/1972', 41956, 4, 2, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Pammi', 'Revel', '09/05/1975', 61297, 5, 11, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Denver', 'Crease', '29/09/1985', 35148, 5, 8, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Sasha', 'Lermouth', '03/03/1982', 53340, 4, 1, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Marin', 'Skipsea', '02/05/1983', 54286, 4, 10, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Jarib', 'Brewis', '22/01/1975', 86784, 3, 1, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Ryun', 'Chapple', '14/11/1972', 86893, 4, 11, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Ermanno', 'Dives', '04/08/1996', 32601, 1, 5, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Flynn', 'Gerasch', '09/08/2002', 44965, 1, 1, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Padraig', 'Horstead', '25/01/2006', 88756, 3, 8, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Pablo', 'enzley', '15/03/1994', 38300, 3, 2, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Shel', 'Virgoe', '27/03/1989', 59879, 1, 10, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Shaw', 'Fishwick', '25/04/1990', 85416, 4, 7, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Nikolas', 'Chubb', '10/03/1985', 76353, 4, 1, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Read', 'Bangs', '10/03/1990', 87080, 4, 9, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Edi', 'Ducker', '13/12/1977', 87220, 2, 4, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Leanor', 'Worvell', '29/07/1996', 85907, 4, 7, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Daune', 'Gerrelt', '12/07/1975', 79341, 1, 3, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Rora', 'Carthy', '19/01/1993', 71214, 3, 3, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Calv', 'Okell', '08/09/1972', 52724, 1, 13, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Lotte', 'Call', '12/02/1997', 70642, 5, 13, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Linette', 'Feria', '27/01/1990', 31053, 4, 6, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Bibby', 'Alliberton', '13/10/2006', 47522, 2, 13, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Duffy', 'Jaggi', '30/06/1983', 97021, 3, 12, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Sayres', 'Antonoczyk', '25/02/1984', 94735, 1, 13, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Alverta', 'Larimer', '08/08/2004', 80850, 2, 13, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Ange', 'Haveline', '24/04/1970', 66262, 3, 8, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Natalie', 'Riveles', '29/08/1978', 92498, 4, 6, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Arlee', 'Cota', '07/02/1995', 62938, 1, 3, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Georg', 'Culverhouse', '23/01/1998', 87330, 5, 11, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Tonia', 'Rouzet', '23/10/1971', 54958, 4, 4, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Harrietta', 'Cumberlidge', '13/01/2003', 97788, 5, 3, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Conroy', 'Umbert', '01/01/2005', 84354, 4, 5, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Steffie', 'Loosemore', '01/10/1994', 59454, 1, 11, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Scottie', 'Bayldon', '07/08/2001', 71777, 2, 2, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Lilas', 'Blackmoor', '01/12/1982', 67180, 1, 9, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Virge', 'Cawdery', '19/04/1971', 57872, 4, 11, null);
insert into policiste (jmeno, prijmeni, datumnarozeni, plat, idstanice, idhodnosti, poznamka) values ('Kennett', 'Minchinden', '05/03/1979', 91896, 3, 4, null);

insert into uzivatele(prihlasovacijmeno,heslo, idopravneni) values('Oli', '12345', 3);

insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (2102115, '01/04/2053', 44);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (9711096, '25/05/2033', 23);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (3831135, '17/06/2040', 33);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (8497601, '10/06/2044', 11);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (9702631, '10/12/2041', 35);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (1485407, '17/10/2047', 21);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (7868188, '25/03/2035', 16);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (5431956, '02/03/2026', 38);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (3210968, '07/04/2042', 13);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (3147076, '14/05/2052', 34);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (8804148, '28/07/2037', 15);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (5200804, '17/11/2037', 46);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (1288275, '13/06/2038', 43);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (9576286, '13/11/2038', 40);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (2891007, '27/09/2054', 37);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (1054396, '25/07/2046', 45);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (1235480, '06/10/2040', 29);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (3463063, '20/09/2047', 47);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (7319738, '18/04/2052', 20);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (8375718, '21/05/2054', 4);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (1665263, '06/09/2046', 26);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (7896280, '05/01/2045', 2);
insert into ridicske_prukazy (cislorp, platnostdo, idpolicisty) values (9965339, '27/06/2032', 7);

insert into evidence_r_prukazu (idtypu, cislorp) values (1, 2102115);
insert into evidence_r_prukazu (idtypu, cislorp) values (1, 9711096);
insert into evidence_r_prukazu (idtypu, cislorp) values (4, 3831135);
insert into evidence_r_prukazu (idtypu, cislorp) values (5, 8497601);
insert into evidence_r_prukazu (idtypu, cislorp) values (1, 9702631);
insert into evidence_r_prukazu (idtypu, cislorp) values (1, 1485407);
insert into evidence_r_prukazu (idtypu, cislorp) values (3, 7868188);
insert into evidence_r_prukazu (idtypu, cislorp) values (3, 5431956);
insert into evidence_r_prukazu (idtypu, cislorp) values (2, 3210968);
insert into evidence_r_prukazu (idtypu, cislorp) values (4, 3147076);
insert into evidence_r_prukazu (idtypu, cislorp) values (1, 8804148);
insert into evidence_r_prukazu (idtypu, cislorp) values (2, 5200804);
insert into evidence_r_prukazu (idtypu, cislorp) values (5, 1288275);
insert into evidence_r_prukazu (idtypu, cislorp) values (1, 1054396);
insert into evidence_r_prukazu (idtypu, cislorp) values (3, 1235480);
insert into evidence_r_prukazu (idtypu, cislorp) values (3, 3463063);
insert into evidence_r_prukazu (idtypu, cislorp) values (1, 7319738);
insert into evidence_r_prukazu (idtypu, cislorp) values (4, 8375718);
insert into evidence_r_prukazu (idtypu, cislorp) values (4, 1665263);
insert into evidence_r_prukazu (idtypu, cislorp) values (2, 7896280);
insert into evidence_r_prukazu (idtypu, cislorp) values (5, 9965339);
insert into evidence_r_prukazu (idtypu, cislorp) values (2, 2102115);
insert into evidence_r_prukazu (idtypu, cislorp) values (4, 9711096);
insert into evidence_r_prukazu (idtypu, cislorp) values (2, 3831135);
insert into evidence_r_prukazu (idtypu, cislorp) values (1, 8497601);

insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (2, 15, 0, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (1, 18, 0, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (6, 14, 0, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (5, 17, 0, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (1, 4, 0, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (2, 30, 0, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (5, 37, 0, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (1, 45, 0, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (2, 34, 0, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (3, 20, 0, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (2, 12, 1, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (3, 19, 1, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (1, 39, 1, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (2, 44, 1, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (5, 9, 1, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (6, 33, 1, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (3, 6, 1, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (6, 30, 1, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (6, 46, 1, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (5, 11, 1, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (2, 24, 2, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (3, 33, 2, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (6, 46, 2, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (6, 36, 2, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (5, 25, 2, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (4, 35, 2, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (4, 27, 2, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (5, 38, 2, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (4, 50, 2, null);
insert into dopravni_prostredky (idbarvy, idpolicisty, discriminator, poznamka) values (5, 31, 2, null);

insert into automobily (idprostredku, poznavaciznacka) values (1, 'O4EUeQGl');
insert into automobily (idprostredku, poznavaciznacka) values (2, 'PGWDsJL7');
insert into automobily (idprostredku, poznavaciznacka) values (3, 'iR65cyg0');
insert into automobily (idprostredku, poznavaciznacka) values (4, 'yKxd6yZq');
insert into automobily (idprostredku, poznavaciznacka) values (5, 'seu3zCU4');
insert into automobily (idprostredku, poznavaciznacka) values (6, 'YNF31izr');
insert into automobily (idprostredku, poznavaciznacka) values (7, 'NzaWzysV');
insert into automobily (idprostredku, poznavaciznacka) values (8, 'x8jL8Yw0');
insert into automobily (idprostredku, poznavaciznacka) values (9, 'dMdZYSDb');
insert into automobily (idprostredku, poznavaciznacka) values (10, 'PMfAb8J4');

insert into motocykly (idprostredku, poznavaciznacka) values (21, 'uM9aO5V');
insert into motocykly (idprostredku, poznavaciznacka) values (22, '73QrSkB');
insert into motocykly (idprostredku, poznavaciznacka) values (23, 'aT8ProS');
insert into motocykly (idprostredku, poznavaciznacka) values (24, 'PNkJ93P');
insert into motocykly (idprostredku, poznavaciznacka) values (25, '2KLodyQ');
insert into motocykly (idprostredku, poznavaciznacka) values (26, 'rqBOTUJ');
insert into motocykly (idprostredku, poznavaciznacka) values (27, 'BKQzWX7');
insert into motocykly (idprostredku, poznavaciznacka) values (28, 'VZzGWgH');
insert into motocykly (idprostredku, poznavaciznacka) values (29, '7D1SWby');
insert into motocykly (idprostredku, poznavaciznacka) values (30, 'ps6SDKN');

insert into kone (idprostredku, jmeno, datumNarozeni) values (11, 'Janelle', '19/09/2001');
insert into kone (idprostredku, jmeno, datumNarozeni) values (12, 'Valdemar', '13/03/2016');
insert into kone (idprostredku, jmeno, datumNarozeni) values (13, 'Obadiah', '15/05/2002');
insert into kone (idprostredku, jmeno, datumNarozeni) values (14, 'Viviene', '18/07/2003');
insert into kone (idprostredku, jmeno, datumNarozeni) values (15, 'Gun', '29/11/1992');
insert into kone (idprostredku, jmeno, datumNarozeni) values (16, 'Anestassia', '16/04/2005');
insert into kone (idprostredku, jmeno, datumNarozeni) values (17, 'Alexandros', '01/07/2007');
insert into kone (idprostredku, jmeno, datumNarozeni) values (18, 'Kennan', '20/04/1996');
insert into kone (idprostredku, jmeno, datumNarozeni) values (19, 'Kylie', '20/07/1992');
insert into kone (idprostredku, jmeno, datumNarozeni) values (20, 'Drucy', '16/07/2013');

insert into hlidky (nazevhlidky, idtypu) values ('Snake', 4);
insert into hlidky (nazevhlidky, idtypu) values ('Monitor', 1);
insert into hlidky (nazevhlidky, idtypu) values ('Hartebeest', 2);
insert into hlidky (nazevhlidky, idtypu) values ('Kangaroo', 4);
insert into hlidky (nazevhlidky, idtypu) values ('Creeper', 4);
insert into hlidky (nazevhlidky, idtypu) values ('Monkey', 2);
insert into hlidky (nazevhlidky, idtypu) values ('Otter', 3);
insert into hlidky (nazevhlidky, idtypu) values ('Trumpeter', 2);
insert into hlidky (nazevhlidky, idtypu) values ('Squirrel', 3);
insert into hlidky (nazevhlidky, idtypu) values ('Tortoise', 1);
insert into hlidky (nazevhlidky, idtypu) values ('Legaan', 3);
insert into hlidky (nazevhlidky, idtypu) values ('Seal', 3);
insert into hlidky (nazevhlidky, idtypu) values ('Reindeer', 2);
insert into hlidky (nazevhlidky, idtypu) values ('Pine squirrel', 4);
insert into hlidky (nazevhlidky, idtypu) values ('Pademelon', 1);
insert into hlidky (nazevhlidky, idtypu) values ('Civet', 3);
insert into hlidky (nazevhlidky, idtypu) values ('Barbet', 4);
insert into hlidky (nazevhlidky, idtypu) values ('Phalarope', 2);
insert into hlidky (nazevhlidky, idtypu) values ('Hedgehog', 3);
insert into hlidky (nazevhlidky, idtypu) values ('Falcon', 2);

insert into okrsky_hlidky (idhlidky, idokrsku) values (13, 4);
insert into okrsky_hlidky (idhlidky, idokrsku) values (6, 8);
insert into okrsky_hlidky (idhlidky, idokrsku) values (3, 8);
insert into okrsky_hlidky (idhlidky, idokrsku) values (18, 5);
insert into okrsky_hlidky (idhlidky, idokrsku) values (2, 3);
insert into okrsky_hlidky (idhlidky, idokrsku) values (12, 8);
insert into okrsky_hlidky (idhlidky, idokrsku) values (8, 1);
insert into okrsky_hlidky (idhlidky, idokrsku) values (14, 4);
insert into okrsky_hlidky (idhlidky, idokrsku) values (13, 8);
insert into okrsky_hlidky (idhlidky, idokrsku) values (2, 1);
insert into okrsky_hlidky (idhlidky, idokrsku) values (19, 8);
insert into okrsky_hlidky (idhlidky, idokrsku) values (18, 8);
insert into okrsky_hlidky (idhlidky, idokrsku) values (3, 6);
insert into okrsky_hlidky (idhlidky, idokrsku) values (4, 3);
insert into okrsky_hlidky (idhlidky, idokrsku) values (11, 8);
insert into okrsky_hlidky (idhlidky, idokrsku) values (5, 8);
insert into okrsky_hlidky (idhlidky, idokrsku) values (14, 1);
insert into okrsky_hlidky (idhlidky, idokrsku) values (10, 1);
insert into okrsky_hlidky (idhlidky, idokrsku) values (10, 4);
insert into okrsky_hlidky (idhlidky, idokrsku) values (12, 4);
insert into okrsky_hlidky (idhlidky, idokrsku) values (17, 7);
insert into okrsky_hlidky (idhlidky, idokrsku) values (9, 1);
insert into okrsky_hlidky (idhlidky, idokrsku) values (6, 2);
insert into okrsky_hlidky (idhlidky, idokrsku) values (5, 4);
insert into okrsky_hlidky (idhlidky, idokrsku) values (4, 2);
insert into okrsky_hlidky (idhlidky, idokrsku) values (12, 7);
insert into okrsky_hlidky (idhlidky, idokrsku) values (13, 3);
insert into okrsky_hlidky (idhlidky, idokrsku) values (10, 5);
insert into okrsky_hlidky (idhlidky, idokrsku) values (15, 2);
insert into okrsky_hlidky (idhlidky, idokrsku) values (7, 2);
insert into okrsky_hlidky (idhlidky, idokrsku) values (16, 7);
insert into okrsky_hlidky (idhlidky, idokrsku) values (10, 3);
insert into okrsky_hlidky (idhlidky, idokrsku) values (18, 2);
insert into okrsky_hlidky (idhlidky, idokrsku) values (7, 5);
insert into okrsky_hlidky (idhlidky, idokrsku) values (11, 4);
insert into okrsky_hlidky (idhlidky, idokrsku) values (18, 6);
insert into okrsky_hlidky (idhlidky, idokrsku) values (8, 2);
insert into okrsky_hlidky (idhlidky, idokrsku) values (9, 7);
insert into okrsky_hlidky (idhlidky, idokrsku) values (20, 6);
insert into okrsky_hlidky (idhlidky, idokrsku) values (19, 6);
insert into okrsky_hlidky (idhlidky, idokrsku) values (11, 1);
insert into okrsky_hlidky (idhlidky, idokrsku) values (17, 3);
insert into okrsky_hlidky (idhlidky, idokrsku) values (5, 7);
insert into okrsky_hlidky (idhlidky, idokrsku) values (7, 4);

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd,casDo) values (1, 40,'01/12/2024',TO_DATE('8:00', 'hh24:mi'),TO_DATE('16:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (1, 27, '01/12/2024',TO_DATE('8:00', 'hh24:mi'),TO_DATE('16:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (1, 42, '01/12/2024',TO_DATE('8:00', 'hh24:mi'),TO_DATE('16:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (2, 47, '11/06/2025',TO_DATE('15:00', 'hh24:mi'),TO_DATE('23:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (2, 8, '11/06/2025',TO_DATE('15:00', 'hh24:mi'),TO_DATE('23:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (2, 14, '11/06/2025',TO_DATE('15:00', 'hh24:mi'),TO_DATE('23:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (3, 32, '08/08/2025',TO_DATE('16:00', 'hh24:mi'),TO_DATE('0:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (3, 24, '08/08/2025',TO_DATE('16:00', 'hh24:mi'),TO_DATE('0:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (3, 9, '08/08/2025',TO_DATE('16:00', 'hh24:mi'),TO_DATE('0:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (4, 39, '22/02/2025',TO_DATE('11:00', 'hh24:mi'),TO_DATE('19:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (4, 2, '22/02/2025',TO_DATE('11:00', 'hh24:mi'),TO_DATE('19:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (4, 50, '22/02/2025',TO_DATE('11:00', 'hh24:mi'),TO_DATE('19:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (5, 49, '07/09/2025',TO_DATE('14:00', 'hh24:mi'),TO_DATE('22:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (5, 29, '07/09/2025',TO_DATE('14:00', 'hh24:mi'),TO_DATE('22:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (5, 35, '07/09/2025',TO_DATE('14:00', 'hh24:mi'),TO_DATE('22:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (6, 10, '22/08/2025',TO_DATE('15:00', 'hh24:mi'),TO_DATE('23:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (6, 20, '22/08/2025',TO_DATE('15:00', 'hh24:mi'),TO_DATE('23:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (6, 46, '22/08/2025',TO_DATE('15:00', 'hh24:mi'),TO_DATE('23:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (7, 3, '18/08/2025',TO_DATE('9:00', 'hh24:mi'),TO_DATE('17:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (7, 30, '18/08/2025',TO_DATE('9:00', 'hh24:mi'),TO_DATE('17:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (7, 14, '18/08/2025',TO_DATE('9:00', 'hh24:mi'),TO_DATE('17:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (8, 49, '18/02/2025',TO_DATE('14:00', 'hh24:mi'),TO_DATE('22:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (8, 36, '18/02/2025',TO_DATE('14:00', 'hh24:mi'),TO_DATE('22:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (8, 5, '18/02/2025',TO_DATE('14:00', 'hh24:mi'),TO_DATE('22:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (9, 46, '20/02/2025',TO_DATE('12:00', 'hh24:mi'), TO_DATE('20:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (9, 28, '20/02/2025',TO_DATE('12:00', 'hh24:mi'), TO_DATE('20:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (9, 20, '20/02/2025',TO_DATE('12:00', 'hh24:mi'), TO_DATE('20:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (10, 43, '15/10/2025',TO_DATE('9:00', 'hh24:mi'), TO_DATE('17:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (10, 8, '15/10/2025',TO_DATE('9:00', 'hh24:mi'), TO_DATE('17:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (10, 24, '15/10/2025',TO_DATE('9:00', 'hh24:mi'), TO_DATE('17:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (11, 2, '04/01/2025',TO_DATE('17:00', 'hh24:mi'), TO_DATE('1:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (11, 21, '04/01/2025',TO_DATE('17:00', 'hh24:mi'), TO_DATE('1:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (12, 6, '20/06/2025',TO_DATE('15:00', 'hh24:mi'),TO_DATE('23:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (12, 3, '20/06/2025',TO_DATE('15:00', 'hh24:mi'),TO_DATE('23:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (13, 24, '15/12/2024',TO_DATE('16:00', 'hh24:mi'),TO_DATE('0:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (13, 17, '15/12/2024',TO_DATE('16:00', 'hh24:mi'),TO_DATE('0:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (14, 18, '20/07/2025',TO_DATE('15:00', 'hh24:mi'),TO_DATE('23:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (14, 41, '20/07/2025',TO_DATE('15:00', 'hh24:mi'),TO_DATE('23:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (15, 9, '11/04/2025',TO_DATE('20:00', 'hh24:mi'),TO_DATE('4:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (15, 35, '11/04/2025',TO_DATE('20:00', 'hh24:mi'),TO_DATE('4:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (16, 22, '12/06/2025',TO_DATE('9:00', 'hh24:mi'),TO_DATE('17:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (16, 36, '12/06/2025',TO_DATE('9:00', 'hh24:mi'),TO_DATE('17:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (17, 27, '01/06/2025',TO_DATE('10:00', 'hh24:mi'),TO_DATE('18:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (17, 19, '01/06/2025',TO_DATE('10:00', 'hh24:mi'),TO_DATE('18:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (18, 23, '28/09/2025',TO_DATE('17:00', 'hh24:mi'),TO_DATE('1:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (18, 32, '28/09/2025',TO_DATE('17:00', 'hh24:mi'),TO_DATE('1:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (19, 4, '22/10/2025',TO_DATE('15:00', 'hh24:mi'),TO_DATE('23:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (19, 14, '22/10/2025',TO_DATE('15:00', 'hh24:mi'),TO_DATE('23:00', 'hh24:mi'));

insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (20, 39, '12/07/2025',TO_DATE('11:00', 'hh24:mi'),TO_DATE('19:00', 'hh24:mi'));
insert into evidence_hlidek (idhlidky, idpolicisty, datum, casOd, casDo) values (20, 9, '12/07/2025',TO_DATE('11:00', 'hh24:mi'),TO_DATE('19:00', 'hh24:mi'));

insert into zasahy (datum, cas, popis, idadresy) values ('27/07/2024', TO_DATE('9:42', 'hh24:mi'), 'presny popis zasahu', 21);
insert into zasahy (datum, cas, popis, idadresy) values ('08/03/2025', TO_DATE('21:30', 'hh24:mi'), 'presny popis zasahu', 12);
insert into zasahy (datum, cas, popis, idadresy) values ('16/03/2025', TO_DATE('10:47', 'hh24:mi'), 'presny popis zasahu', 18);
insert into zasahy (datum, cas, popis, idadresy) values ('29/08/2025', TO_DATE('0:18', 'hh24:mi'), 'presny popis zasahu', 7);
insert into zasahy (datum, cas, popis, idadresy) values ('11/12/2023', TO_DATE('17:53', 'hh24:mi'), 'presny popis zasahu', 24);
insert into zasahy (datum, cas, popis, idadresy) values ('17/11/2024', TO_DATE('3:36', 'hh24:mi'), 'presny popis zasahu', 17);
insert into zasahy (datum, cas, popis, idadresy) values ('29/10/2024', TO_DATE('22:55', 'hh24:mi'), 'presny popis zasahu', 29);
insert into zasahy (datum, cas, popis, idadresy) values ('13/07/2024', TO_DATE('18:01', 'hh24:mi'), 'presny popis zasahu', 10);
insert into zasahy (datum, cas, popis, idadresy) values ('02/01/2024', TO_DATE('2:53', 'hh24:mi'), 'presny popis zasahu', 16);
insert into zasahy (datum, cas, popis, idadresy) values ('27/06/2024', TO_DATE('13:40', 'hh24:mi'), 'presny popis zasahu', 3);
insert into zasahy (datum, cas, popis, idadresy) values ('01/06/2024', TO_DATE('4:11', 'hh24:mi'), 'presny popis zasahu', 5);
insert into zasahy (datum, cas, popis, idadresy) values ('22/09/2025', TO_DATE('7:29', 'hh24:mi'), 'presny popis zasahu', 11);
insert into zasahy (datum, cas, popis, idadresy) values ('27/06/2025', TO_DATE('22:34', 'hh24:mi'), 'presny popis zasahu', 28);
insert into zasahy (datum, cas, popis, idadresy) values ('22/04/2024', TO_DATE('6:47', 'hh24:mi'), 'presny popis zasahu', 49);
insert into zasahy (datum, cas, popis, idadresy) values ('12/07/2024', TO_DATE('3:10', 'hh24:mi'), 'presny popis zasahu', 37);
insert into zasahy (datum, cas, popis, idadresy) values ('16/09/2024',TO_DATE('5:37', 'hh24:mi'), 'presny popis zasahu', 33);
insert into zasahy (datum, cas, popis, idadresy) values ('14/11/2025',TO_DATE('13:20', 'hh24:mi'), 'presny popis zasahu', 17);
insert into zasahy (datum, cas, popis, idadresy) values ('31/10/2024',TO_DATE('21:06', 'hh24:mi'), 'presny popis zasahu', 48);
insert into zasahy (datum, cas, popis, idadresy) values ('26/08/2024',TO_DATE('14:40', 'hh24:mi'), 'presny popis zasahu', 25);
insert into zasahy (datum, cas, popis, idadresy) values ('09/12/2024',TO_DATE('17:50', 'hh24:mi'), 'presny popis zasahu', 43);

insert into evidence_zasahu (idzasahu, idhlidky) values (1, 9);
insert into evidence_zasahu (idzasahu, idhlidky) values (2, 14);
insert into evidence_zasahu (idzasahu, idhlidky) values (3, 11);
insert into evidence_zasahu (idzasahu, idhlidky) values (4, 11);
insert into evidence_zasahu (idzasahu, idhlidky) values (5, 10);
insert into evidence_zasahu (idzasahu, idhlidky) values (6, 20);
insert into evidence_zasahu (idzasahu, idhlidky) values (7, 8);
insert into evidence_zasahu (idzasahu, idhlidky) values (8, 19);
insert into evidence_zasahu (idzasahu, idhlidky) values (9, 12);
insert into evidence_zasahu (idzasahu, idhlidky) values (10, 11);
insert into evidence_zasahu (idzasahu, idhlidky) values (11, 1);
insert into evidence_zasahu (idzasahu, idhlidky) values (12, 12);
insert into evidence_zasahu (idzasahu, idhlidky) values (13, 19);
insert into evidence_zasahu (idzasahu, idhlidky) values (14, 7);
insert into evidence_zasahu (idzasahu, idhlidky) values (15, 17);
insert into evidence_zasahu (idzasahu, idhlidky) values (16, 19);
insert into evidence_zasahu (idzasahu, idhlidky) values (17, 6);
insert into evidence_zasahu (idzasahu, idhlidky) values (18, 20);
insert into evidence_zasahu (idzasahu, idhlidky) values (19, 13);
insert into evidence_zasahu (idzasahu, idhlidky) values (20, 14);

insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (4, 2, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (14, 4, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (19, 3, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (10, 3, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (10, 5, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (18, 2, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (11, 5, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (12, 1, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (18, 2, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (20, 4, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (13, 3, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (10, 3, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (1, 3, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (20, 5, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (5, 2, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (10, 2, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (9, 2, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (2, 2, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (19, 3, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (8, 3, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (7, 3, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (16, 3, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (1, 4, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (19, 4, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (10, 5, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (1, 1, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (15, 3, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (2, 3, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (6, 1, null);
insert into prestupky (idzasahu, idtypuprestupku, poznamka) values (13, 1, null);

insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Emmy', 'Le Fevre', 90861, null, 2);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Bride', 'Hamm', 82135, null, 48);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Sofie', 'Grasner', 35316, null, 20);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Gerri', 'Haylett', 13101, null, 14);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Jaynell', 'Stolberg', 25695, null, 33);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Petra', 'Ewington', 85256, null, 40);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Demott', 'Saiz', 30483, null, 26);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Ricky', 'Rhodus', 44289, null, 25);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Ham', 'Copeman', 72990, null, 32);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Roxana', 'Wimpey', 63665, null, 30);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Matthiew', 'Ciccottio', 70920, null, 13);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Ignaz', 'Qualtro', 50914, null, 29);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Golda', 'MacTimpany', 36621, null, 19);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Serge', 'Chaffe', 45973, null, 23);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Griffy', 'Godding', 60293, null, 38);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Nancy', 'Morais', 51107, null, 31);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Livvyy', 'Chillingworth', 73443, null, 41);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Diego', 'Golda', 46219, null, 18);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Nahum', 'Dewis', 49626, null, 34);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Leopold', 'Pegg', 47893, null, 37);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Engelbert', 'Trimbey', 58682, null, 40);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Katleen', 'Maghull', 13674, null, 45);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Dru', 'Tythacott', 54443, null, 27);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Kincaid', 'Bexon', 81246, null, 23);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Vlad', 'Thorp', 63870, null, 36);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Lorens', 'Beiderbeck', 78312, null, 47);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Freeman', 'Gostyke', 62532, null, 35);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Christian', 'Chicchetto', 82637, null, 16);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Margarete', 'Ballach', 93940, null, 48);
insert into obcane (jmeno, prijmeni, cisloop, poznamka, idadresy) values ('Eleanore', 'Blanckley', 47014, null, 27);

insert into prestupky_obcanu (idobcana, idprestupku, datum) values (3, 8, '07/12/2023');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (29, 4, '01/04/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (24, 6, '17/08/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (5, 8, '26/04/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (15, 18, '02/10/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (29, 3, '05/07/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (18, 1, '25/10/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (17, 4, '13/04/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (23, 10, '11/06/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (23, 12, '05/12/2023');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (28, 6, '04/06/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (7, 9, '02/01/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (15, 13, '17/11/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (17, 5, '26/04/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (29, 13, '13/06/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (22, 15, '12/09/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (27, 15, '17/04/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (8, 10, '21/01/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (1, 8, '11/09/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (10, 10, '20/10/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (25, 3, '05/10/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (26, 14, '22/08/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (11, 9, '30/09/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (12, 2, '17/04/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (26, 13, '06/02/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (6, 16, '02/10/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (30, 16, '19/03/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (21, 17, '21/01/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (12, 14, '28/02/2024');
insert into prestupky_obcanu (idobcana, idprestupku, datum) values (9, 19, '20/12/2023');

insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '30/11/2024', null, 3, 8);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '05/06/2024', null, 29, 4);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '24/10/2024', null, 24, 6);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '28/08/2024', null, 5, 8);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '20/06/2024', null, 15, 18);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '07/07/2024', null, 29, 3);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '28/12/2023', null, 18, 1);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '08/12/2023', null, 17, 4);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '17/12/2023', null, 23, 10);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '20/06/2024', null, 23, 12);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '13/12/2023', null, 28, 6);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '10/01/2024', null, 7, 9);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '05/10/2024', null, 15, 13);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '01/02/2024', null, 17, 5);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '25/04/2024', null, 29, 13);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '03/07/2024', null, 22, 15);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '27/03/2024', null, 27, 15);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '31/12/2023', null, 8, 10);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '29/07/2024', null, 1, 8);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '30/11/2024', null, 10, 10);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '28/12/2023', null, 25, 3);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '27/08/2024', null, 26, 14);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '05/06/2024', null, 11, 9);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '18/11/2024', null, 12, 2);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '27/11/2024', null, 26, 13);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '21/03/2024', null, 6, 16);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '02/03/2024', null, 30, 16);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '11/02/2024', null, 21, 17);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '13/04/2024', null, 12, 14);
insert into komunikace (zprava, datum, poznamka, idobcana, idprestupku) values ('zprava pro obcana', '07/03/2024', null, 9, 19);